# Generated by Django 6.0.3 on 2026-06-13 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_branch_options'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch', 'date', 'status'], name='finance_exp_branch__e3926e_idx'),
        ),
    ]
