# Generated by Django 6.0.3 on 2026-06-13 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'ordering': ['-performed_at']},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'ordering': ['next_due_date']},
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['is_active', 'next_due_date'], name='assets_main_is_acti_e6a9e7_idx'),
        ),
    ]
