# Generated by Django 6.0.3 on 2026-06-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_seatingarrangement_id_alter_table_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatingarrangement',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tableseat',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='seatingarrangement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tableseat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
