# Generated by Django 6.0.3 on 2026-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_branch_options'),
        ('tables', '0003_alter_seatingarrangement_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['branch', 'status'], name='tables_tabl_branch__172da6_idx'),
        ),
    ]
