# Generated by Django 6.0.3 on 2026-06-13 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_branch_options'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='wastagelog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['branch', 'is_active'], name='inventory_i_branch__2c553b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['ingredient', '-created_at'], name='inventory_s_ingredi_d1cfdd_idx'),
        ),
    ]
