# Generated by Django 6.0.3 on 2026-06-13 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_branch_options'),
        ('pos', '0002_notification_alter_bot_id_alter_kot_id_alter_meal_id_and_more'),
        ('tables', '0003_alter_seatingarrangement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status'], name='pos_order_branch__1a1075_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', '-created_at'], name='pos_order_branch__9d1ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['branch', 'reservation_date', 'status'], name='pos_reserva_branch__6e1ffc_idx'),
        ),
    ]
