# Generated by Django 5.1.6 on 2026-06-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_options_alter_menuitem_options'),
        ('pos', '0003_order_pos_order_branch__1a1075_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem'),
        ),
    ]
