# Generated by Django 5.1.6 on 2026-06-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_id_alter_menuitem_id_alter_menusection_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-created_at']},
        ),
    ]
